// Updated interfaces for NoSQL structure
export interface Lesson {
  id?: string;
  title: string;
  description: string;
  filename: string;
  duration: number; // in seconds
  order: number;
  status: "processing" | "processed";
  url?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Chapter {
  id?: string;
  title: string;
  description: string;
  order: number;
  starterCodeUrl?: string;
  finalCodeUrl?: string;
  lessons: Lesson[]; // Embedded lessons array
  createdAt: string;
  updatedAt: string;
}

export interface Course {
  id?: string;
  title: string;
  slug: string;
  description: string;
  thumbnailUrl?: string;
  hours: number;
  level: "easy" | "medium" | "hard";
  createdBy: string;
  chapters: Chapter[]; // Embedded chapters array
  createdAt: string;
  updatedAt: string;
}

// Mock data with embedded structure
export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Complete Node.js Developer Course",
    slug: "nodejs-basics",
    description:
      "Master Node.js from basics to advanced concepts including Express.js, MongoDB, and authentication.",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop",
    hours: 25,
    level: "medium",
    createdBy: "John Doe",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    chapters: [
      {
        id: "1",
        title: "Node.js Fundamentals",
        description: "Learn the basics of Node.js runtime and core concepts",
        order: 1,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-01-15T14:00:00Z",
        lessons: [
          {
            id: "1",
            title: "What is Node.js?",
            description: "Understanding Node.js runtime and its use cases",
            filename: "what-is-nodejs.mp4",
            duration: 420,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/what-is-nodejs.mp4",
            createdAt: "2024-01-15T10:00:00Z",
            updatedAt: "2024-01-15T11:00:00Z",
          },
          {
            id: "2",
            title: "Installing Node.js and npm",
            description:
              "Setting up Node.js development environment and package manager",
            filename: "nodejs-installation.mp4",
            duration: 600,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/nodejs-installation.mp4",
            createdAt: "2024-01-15T11:00:00Z",
            updatedAt: "2024-01-15T12:00:00Z",
          },
          {
            id: "3",
            title: "Your First Node.js Application",
            description: "Creating and running your first Node.js script",
            filename: "first-nodejs-app.mp4",
            duration: 480,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/first-nodejs-app.mp4",
            createdAt: "2024-01-15T12:00:00Z",
            updatedAt: "2024-01-15T13:00:00Z",
          },
          {
            id: "4",
            title: "Understanding the Event Loop",
            description: "How Node.js handles asynchronous operations",
            filename: "event-loop.mp4",
            duration: 540,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/event-loop.mp4",
            createdAt: "2024-01-15T13:00:00Z",
            updatedAt: "2024-01-15T14:00:00Z",
          },
        ],
      },
      {
        id: "2",
        title: "Core Node.js Modules",
        description:
          "Working with built-in Node.js modules for file system, paths, and streams",
        order: 2,
        createdAt: "2024-01-16T10:00:00Z",
        updatedAt: "2024-01-16T13:00:00Z",
        lessons: [
          {
            id: "5",
            title: "Working with File System",
            description: "Reading and writing files using fs module",
            filename: "file-system.mp4",
            duration: 720,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/file-system.mp4",
            createdAt: "2024-01-16T10:00:00Z",
            updatedAt: "2024-01-16T11:00:00Z",
          },
          {
            id: "6",
            title: "Path and URL Modules",
            description: "Working with file paths and URL manipulation",
            filename: "path-url-modules.mp4",
            duration: 360,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/path-url-modules.mp4",
            createdAt: "2024-01-16T11:00:00Z",
            updatedAt: "2024-01-16T12:00:00Z",
          },
          {
            id: "7",
            title: "Streams and Buffers",
            description: "Understanding data streams and buffer operations",
            filename: "streams-buffers.mp4",
            duration: 660,
            order: 3,
            status: "processing",
            createdAt: "2024-01-16T12:00:00Z",
            updatedAt: "2024-01-16T13:00:00Z",
          },
        ],
      },
      {
        id: "3",
        title: "HTTP and Web Servers",
        description:
          "Building HTTP servers and handling web requests with Node.js",
        order: 3,
        createdAt: "2024-01-17T10:00:00Z",
        updatedAt: "2024-01-17T13:00:00Z",
        lessons: [
          {
            id: "8",
            title: "Creating HTTP Server",
            description: "Building your first HTTP server with Node.js",
            filename: "http-server.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/http-server.mp4",
            createdAt: "2024-01-17T10:00:00Z",
            updatedAt: "2024-01-17T11:00:00Z",
          },
          {
            id: "9",
            title: "Handling HTTP Requests",
            description: "Processing GET, POST, and other HTTP methods",
            filename: "http-requests.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/http-requests.mp4",
            createdAt: "2024-01-17T11:00:00Z",
            updatedAt: "2024-01-17T12:00:00Z",
          },
          {
            id: "10",
            title: "URL Routing Basics",
            description: "Implementing basic routing without frameworks",
            filename: "url-routing.mp4",
            duration: 540,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/url-routing.mp4",
            createdAt: "2024-01-17T12:00:00Z",
            updatedAt: "2024-01-17T13:00:00Z",
          },
        ],
      },
      {
        id: "4",
        title: "Express.js Framework",
        description: "Building web applications with Express.js framework",
        order: 4,
        createdAt: "2024-01-18T10:00:00Z",
        updatedAt: "2024-01-18T13:00:00Z",
        lessons: [
          {
            id: "11",
            title: "Introduction to Express.js",
            description: "Setting up Express.js and understanding its benefits",
            filename: "express-intro.mp4",
            duration: 480,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/express-intro.mp4",
            createdAt: "2024-01-18T10:00:00Z",
            updatedAt: "2024-01-18T11:00:00Z",
          },
          {
            id: "12",
            title: "Express Middleware",
            description:
              "Understanding and creating custom middleware functions",
            filename: "express-middleware.mp4",
            duration: 660,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/express-middleware.mp4",
            createdAt: "2024-01-18T11:00:00Z",
            updatedAt: "2024-01-18T12:00:00Z",
          },
          {
            id: "13",
            title: "Building RESTful APIs",
            description: "Creating REST endpoints with Express.js",
            filename: "restful-apis.mp4",
            duration: 780,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/restful-apis.mp4",
            createdAt: "2024-01-18T12:00:00Z",
            updatedAt: "2024-01-18T13:00:00Z",
          },
        ],
      },
      {
        id: "5",
        title: "Database Integration",
        description: "Working with MongoDB and Mongoose for data persistence",
        order: 5,
        createdAt: "2024-01-19T10:00:00Z",
        updatedAt: "2024-01-19T13:00:00Z",
        lessons: [
          {
            id: "14",
            title: "Introduction to MongoDB",
            description: "Understanding NoSQL databases and MongoDB basics",
            filename: "mongodb-intro.mp4",
            duration: 540,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/mongodb-intro.mp4",
            createdAt: "2024-01-19T10:00:00Z",
            updatedAt: "2024-01-19T11:00:00Z",
          },
          {
            id: "15",
            title: "Mongoose ODM",
            description: "Using Mongoose for MongoDB object modeling",
            filename: "mongoose-odm.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/mongoose-odm.mp4",
            createdAt: "2024-01-19T11:00:00Z",
            updatedAt: "2024-01-19T12:00:00Z",
          },
          {
            id: "16",
            title: "CRUD Operations",
            description: "Implementing Create, Read, Update, Delete operations",
            filename: "crud-operations.mp4",
            duration: 840,
            order: 3,
            status: "processing",
            createdAt: "2024-01-19T12:00:00Z",
            updatedAt: "2024-01-19T13:00:00Z",
          },
        ],
      },
      {
        id: "6",
        title: "Authentication & Security",
        description:
          "Implementing user authentication and securing Node.js applications",
        order: 6,
        createdAt: "2024-01-20T10:00:00Z",
        updatedAt: "2024-01-20T14:00:00Z",
        lessons: [
          {
            id: "17",
            title: "User Authentication Basics",
            description:
              "Understanding authentication concepts and implementation",
            filename: "auth-basics.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/auth-basics.mp4",
            createdAt: "2024-01-20T10:00:00Z",
            updatedAt: "2024-01-20T11:00:00Z",
          },
          {
            id: "18",
            title: "JWT Token Implementation",
            description: "Working with JSON Web Tokens for authentication",
            filename: "jwt-tokens.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/jwt-tokens.mp4",
            createdAt: "2024-01-20T11:00:00Z",
            updatedAt: "2024-01-20T12:00:00Z",
          },
          {
            id: "19",
            title: "Password Hashing and Security",
            description: "Implementing secure password storage and validation",
            filename: "password-security.mp4",
            duration: 540,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/password-security.mp4",
            createdAt: "2024-01-20T12:00:00Z",
            updatedAt: "2024-01-20T13:00:00Z",
          },
          {
            id: "20",
            title: "API Security Best Practices",
            description:
              "Implementing security measures for Node.js applications",
            filename: "api-security.mp4",
            duration: 660,
            order: 4,
            status: "processing",
            createdAt: "2024-01-20T13:00:00Z",
            updatedAt: "2024-01-20T14:00:00Z",
          },
        ],
      },
    ],
  },

  {
    id: "2",
    title: "Complete HTML & CSS Mastery Course",
    slug: "html-css-complete",
    description:
      "Master HTML and CSS from fundamentals to advanced responsive design, animations, and modern layout techniques.",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop",
    hours: 18,
    level: "easy",
    createdBy: "Sarah Johnson",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-10T16:00:00Z",
    chapters: [
      {
        id: "1",
        title: "HTML Fundamentals",
        description:
          "Learn the building blocks of web pages with HTML structure and semantics",
        order: 1,
        starterCodeUrl: "https://github.com/example/html-fundamentals-starter",
        finalCodeUrl: "https://github.com/example/html-fundamentals-final",
        createdAt: "2024-02-01T09:00:00Z",
        updatedAt: "2024-02-01T15:00:00Z",
        lessons: [
          {
            id: "1",
            title: "What is HTML?",
            description:
              "Understanding HTML structure, elements, and the role in web development",
            filename: "what-is-html.mp4",
            duration: 360,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/what-is-html.mp4",
            createdAt: "2024-02-01T09:00:00Z",
            updatedAt: "2024-02-01T10:00:00Z",
          },
          {
            id: "2",
            title: "HTML Document Structure",
            description: "DOCTYPE, html, head, and body elements explained",
            filename: "html-document-structure.mp4",
            duration: 480,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/html-document-structure.mp4",
            createdAt: "2024-02-01T10:00:00Z",
            updatedAt: "2024-02-01T11:00:00Z",
          },
          {
            id: "3",
            title: "HTML Tags and Elements",
            description:
              "Working with paragraphs, headings, links, and basic formatting",
            filename: "html-tags-elements.mp4",
            duration: 540,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/html-tags-elements.mp4",
            createdAt: "2024-02-01T11:00:00Z",
            updatedAt: "2024-02-01T12:00:00Z",
          },
          {
            id: "4",
            title: "HTML Attributes",
            description:
              "Understanding attributes, classes, IDs, and data attributes",
            filename: "html-attributes.mp4",
            duration: 420,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/html-attributes.mp4",
            createdAt: "2024-02-01T12:00:00Z",
            updatedAt: "2024-02-01T13:00:00Z",
          },
          {
            id: "5",
            title: "Lists and Tables",
            description:
              "Creating ordered lists, unordered lists, and HTML tables",
            filename: "lists-tables.mp4",
            duration: 600,
            order: 5,
            status: "processed",
            url: "https://example.com/lessons/lists-tables.mp4",
            createdAt: "2024-02-01T13:00:00Z",
            updatedAt: "2024-02-01T14:00:00Z",
          },
        ],
      },
      {
        id: "2",
        title: "HTML Forms and Media",
        description:
          "Working with forms, inputs, images, audio, and video elements",
        order: 2,
        starterCodeUrl: "https://github.com/example/html-forms-starter",
        finalCodeUrl: "https://github.com/example/html-forms-final",
        createdAt: "2024-02-02T09:00:00Z",
        updatedAt: "2024-02-02T14:00:00Z",
        lessons: [
          {
            id: "6",
            title: "Images and Media Elements",
            description: "Adding images, audio, and video to web pages",
            filename: "images-media.mp4",
            duration: 540,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/images-media.mp4",
            createdAt: "2024-02-02T09:00:00Z",
            updatedAt: "2024-02-02T10:00:00Z",
          },
          {
            id: "7",
            title: "HTML Forms Basics",
            description:
              "Creating forms with input fields, labels, and buttons",
            filename: "html-forms-basics.mp4",
            duration: 660,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/html-forms-basics.mp4",
            createdAt: "2024-02-02T10:00:00Z",
            updatedAt: "2024-02-02T11:00:00Z",
          },
          {
            id: "8",
            title: "Advanced Form Elements",
            description:
              "Working with select dropdowns, checkboxes, radio buttons, and textareas",
            filename: "advanced-form-elements.mp4",
            duration: 600,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/advanced-form-elements.mp4",
            createdAt: "2024-02-02T11:00:00Z",
            updatedAt: "2024-02-02T12:00:00Z",
          },
          {
            id: "9",
            title: "Form Validation",
            description: "HTML5 form validation attributes and techniques",
            filename: "form-validation.mp4",
            duration: 480,
            order: 4,
            status: "processing",
            createdAt: "2024-02-02T12:00:00Z",
            updatedAt: "2024-02-02T13:00:00Z",
          },
        ],
      },
      {
        id: "3",
        title: "CSS Fundamentals",
        description:
          "Introduction to CSS styling, selectors, and basic properties",
        order: 3,
        starterCodeUrl: "https://github.com/example/css-fundamentals-starter",
        finalCodeUrl: "https://github.com/example/css-fundamentals-final",
        createdAt: "2024-02-03T09:00:00Z",
        updatedAt: "2024-02-03T15:00:00Z",
        lessons: [
          {
            id: "10",
            title: "Introduction to CSS",
            description: "What is CSS and how it works with HTML",
            filename: "intro-to-css.mp4",
            duration: 420,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/intro-to-css.mp4",
            createdAt: "2024-02-03T09:00:00Z",
            updatedAt: "2024-02-03T10:00:00Z",
          },
          {
            id: "11",
            title: "CSS Selectors",
            description:
              "Element, class, ID, and attribute selectors explained",
            filename: "css-selectors.mp4",
            duration: 600,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/css-selectors.mp4",
            createdAt: "2024-02-03T10:00:00Z",
            updatedAt: "2024-02-03T11:00:00Z",
          },
          {
            id: "12",
            title: "Colors and Typography",
            description: "Working with colors, fonts, and text properties",
            filename: "colors-typography.mp4",
            duration: 720,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/colors-typography.mp4",
            createdAt: "2024-02-03T11:00:00Z",
            updatedAt: "2024-02-03T12:00:00Z",
          },
          {
            id: "13",
            title: "CSS Box Model",
            description:
              "Understanding margin, padding, border, and content areas",
            filename: "css-box-model.mp4",
            duration: 660,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/css-box-model.mp4",
            createdAt: "2024-02-03T12:00:00Z",
            updatedAt: "2024-02-03T13:00:00Z",
          },
          {
            id: "14",
            title: "CSS Units and Values",
            description: "Pixels, percentages, em, rem, and other CSS units",
            filename: "css-units-values.mp4",
            duration: 480,
            order: 5,
            status: "processed",
            url: "https://example.com/lessons/css-units-values.mp4",
            createdAt: "2024-02-03T13:00:00Z",
            updatedAt: "2024-02-03T14:00:00Z",
          },
        ],
      },
      {
        id: "4",
        title: "CSS Layout Techniques",
        description: "Master CSS layout with Flexbox, Grid, and positioning",
        order: 4,
        starterCodeUrl: "https://github.com/example/css-layout-starter",
        finalCodeUrl: "https://github.com/example/css-layout-final",
        createdAt: "2024-02-04T09:00:00Z",
        updatedAt: "2024-02-04T16:00:00Z",
        lessons: [
          {
            id: "15",
            title: "CSS Positioning",
            description:
              "Static, relative, absolute, and fixed positioning explained",
            filename: "css-positioning.mp4",
            duration: 720,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/css-positioning.mp4",
            createdAt: "2024-02-04T09:00:00Z",
            updatedAt: "2024-02-04T10:00:00Z",
          },
          {
            id: "16",
            title: "Flexbox Fundamentals",
            description: "Introduction to CSS Flexbox layout system",
            filename: "flexbox-fundamentals.mp4",
            duration: 840,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/flexbox-fundamentals.mp4",
            createdAt: "2024-02-04T10:00:00Z",
            updatedAt: "2024-02-04T11:30:00Z",
          },
          {
            id: "17",
            title: "Advanced Flexbox",
            description: "Flex properties, alignment, and complex layouts",
            filename: "advanced-flexbox.mp4",
            duration: 780,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/advanced-flexbox.mp4",
            createdAt: "2024-02-04T11:30:00Z",
            updatedAt: "2024-02-04T13:00:00Z",
          },
          {
            id: "18",
            title: "CSS Grid Layout",
            description: "Creating complex layouts with CSS Grid",
            filename: "css-grid-layout.mp4",
            duration: 900,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/css-grid-layout.mp4",
            createdAt: "2024-02-04T13:00:00Z",
            updatedAt: "2024-02-04T14:30:00Z",
          },
          {
            id: "19",
            title: "Grid vs Flexbox",
            description: "When to use Grid vs Flexbox for different layouts",
            filename: "grid-vs-flexbox.mp4",
            duration: 540,
            order: 5,
            status: "processing",
            createdAt: "2024-02-04T14:30:00Z",
            updatedAt: "2024-02-04T15:30:00Z",
          },
        ],
      },
      {
        id: "5",
        title: "Responsive Design",
        description:
          "Creating websites that work on all devices and screen sizes",
        order: 5,
        starterCodeUrl: "https://github.com/example/responsive-design-starter",
        finalCodeUrl: "https://github.com/example/responsive-design-final",
        createdAt: "2024-02-05T09:00:00Z",
        updatedAt: "2024-02-05T14:00:00Z",
        lessons: [
          {
            id: "20",
            title: "Mobile-First Design",
            description:
              "Understanding mobile-first approach and viewport meta tag",
            filename: "mobile-first-design.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/mobile-first-design.mp4",
            createdAt: "2024-02-05T09:00:00Z",
            updatedAt: "2024-02-05T10:00:00Z",
          },
          {
            id: "21",
            title: "Media Queries",
            description: "Using media queries for responsive breakpoints",
            filename: "media-queries.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/media-queries.mp4",
            createdAt: "2024-02-05T10:00:00Z",
            updatedAt: "2024-02-05T11:00:00Z",
          },
          {
            id: "22",
            title: "Responsive Images",
            description:
              "Making images responsive with srcset and picture elements",
            filename: "responsive-images.mp4",
            duration: 540,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/responsive-images.mp4",
            createdAt: "2024-02-05T11:00:00Z",
            updatedAt: "2024-02-05T12:00:00Z",
          },
          {
            id: "23",
            title: "Responsive Typography",
            description: "Fluid typography and responsive text sizing",
            filename: "responsive-typography.mp4",
            duration: 480,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/responsive-typography.mp4",
            createdAt: "2024-02-05T12:00:00Z",
            updatedAt: "2024-02-05T13:00:00Z",
          },
        ],
      },
      {
        id: "6",
        title: "CSS Animations and Effects",
        description:
          "Adding life to websites with CSS transitions, animations, and transforms",
        order: 6,
        starterCodeUrl: "https://github.com/example/css-animations-starter",
        finalCodeUrl: "https://github.com/example/css-animations-final",
        createdAt: "2024-02-06T09:00:00Z",
        updatedAt: "2024-02-06T15:00:00Z",
        lessons: [
          {
            id: "24",
            title: "CSS Transforms",
            description:
              "2D and 3D transforms: translate, rotate, scale, and skew",
            filename: "css-transforms.mp4",
            duration: 660,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/css-transforms.mp4",
            createdAt: "2024-02-06T09:00:00Z",
            updatedAt: "2024-02-06T10:00:00Z",
          },
          {
            id: "25",
            title: "CSS Transitions",
            description: "Smooth transitions between CSS property changes",
            filename: "css-transitions.mp4",
            duration: 600,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/css-transitions.mp4",
            createdAt: "2024-02-06T10:00:00Z",
            updatedAt: "2024-02-06T11:00:00Z",
          },
          {
            id: "26",
            title: "CSS Animations",
            description:
              "Creating keyframe animations and animation properties",
            filename: "css-animations.mp4",
            duration: 780,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/css-animations.mp4",
            createdAt: "2024-02-06T11:00:00Z",
            updatedAt: "2024-02-06T12:30:00Z",
          },
          {
            id: "27",
            title: "Advanced Animation Techniques",
            description:
              "Animation timing functions, delays, and complex sequences",
            filename: "advanced-animations.mp4",
            duration: 720,
            order: 4,
            status: "processing",
            createdAt: "2024-02-06T12:30:00Z",
            updatedAt: "2024-02-06T14:00:00Z",
          },
          {
            id: "28",
            title: "Performance and Best Practices",
            description:
              "Optimizing animations for performance and accessibility",
            filename: "animation-performance.mp4",
            duration: 540,
            order: 5,
            status: "processing",
            createdAt: "2024-02-06T14:00:00Z",
            updatedAt: "2024-02-06T15:00:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    title: "React Basics - Complete Beginner Course",
    slug: "reactjs-basics",
    description:
      "Learn React from scratch including components, state, props, hooks, and building your first React applications.",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=250&fit=crop",
    hours: 18,
    level: "easy",
    createdBy: "Sarah Johnson",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-08T16:00:00Z",
    chapters: [
      {
        id: "7",
        title: "Introduction to React",
        description:
          "Understanding what React is and setting up your development environment",
        order: 1,
        createdAt: "2024-02-01T09:00:00Z",
        updatedAt: "2024-02-01T13:00:00Z",
        lessons: [
          {
            id: "21",
            title: "What is React?",
            description: "Introduction to React library and its ecosystem",
            filename: "what-is-react.mp4",
            duration: 360,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/what-is-react.mp4",
            createdAt: "2024-02-01T09:00:00Z",
            updatedAt: "2024-02-01T10:00:00Z",
          },
          {
            id: "22",
            title: "Setting up React Development Environment",
            description:
              "Installing Node.js, npm, and creating your first React app",
            filename: "react-setup.mp4",
            duration: 540,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/react-setup.mp4",
            createdAt: "2024-02-01T10:00:00Z",
            updatedAt: "2024-02-01T11:00:00Z",
          },
          {
            id: "23",
            title: "Understanding JSX",
            description: "Learning JSX syntax and how it differs from HTML",
            filename: "understanding-jsx.mp4",
            duration: 480,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/understanding-jsx.mp4",
            createdAt: "2024-02-01T11:00:00Z",
            updatedAt: "2024-02-01T12:00:00Z",
          },
          {
            id: "24",
            title: "Your First React Component",
            description: "Creating and rendering your first React component",
            filename: "first-component.mp4",
            duration: 420,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/first-component.mp4",
            createdAt: "2024-02-01T12:00:00Z",
            updatedAt: "2024-02-01T13:00:00Z",
          },
        ],
      },
      {
        id: "8",
        title: "Components and Props",
        description:
          "Understanding React components and how to pass data between them",
        order: 2,
        createdAt: "2024-02-02T09:00:00Z",
        updatedAt: "2024-02-02T14:00:00Z",
        lessons: [
          {
            id: "25",
            title: "Functional vs Class Components",
            description:
              "Understanding different ways to create React components",
            filename: "functional-vs-class.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/functional-vs-class.mp4",
            createdAt: "2024-02-02T09:00:00Z",
            updatedAt: "2024-02-02T10:00:00Z",
          },
          {
            id: "26",
            title: "Understanding Props",
            description: "Passing data to components using props",
            filename: "understanding-props.mp4",
            duration: 540,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/understanding-props.mp4",
            createdAt: "2024-02-02T10:00:00Z",
            updatedAt: "2024-02-02T11:00:00Z",
          },
          {
            id: "27",
            title: "Props Validation with PropTypes",
            description: "Adding type checking to your React components",
            filename: "prop-types.mp4",
            duration: 420,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/prop-types.mp4",
            createdAt: "2024-02-02T11:00:00Z",
            updatedAt: "2024-02-02T12:00:00Z",
          },
          {
            id: "28",
            title: "Component Composition",
            description: "Building complex UIs by composing smaller components",
            filename: "component-composition.mp4",
            duration: 660,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/component-composition.mp4",
            createdAt: "2024-02-02T12:00:00Z",
            updatedAt: "2024-02-02T13:00:00Z",
          },
          {
            id: "29",
            title: "Children Props",
            description:
              "Working with children props for flexible component design",
            filename: "children-props.mp4",
            duration: 480,
            order: 5,
            status: "processing",
            createdAt: "2024-02-02T13:00:00Z",
            updatedAt: "2024-02-02T14:00:00Z",
          },
        ],
      },
      {
        id: "9",
        title: "State Management",
        description:
          "Managing component state and understanding React's state system",
        order: 3,
        createdAt: "2024-02-03T09:00:00Z",
        updatedAt: "2024-02-03T15:00:00Z",
        lessons: [
          {
            id: "30",
            title: "Understanding State",
            description: "Introduction to React state and when to use it",
            filename: "understanding-state.mp4",
            duration: 540,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/understanding-state.mp4",
            createdAt: "2024-02-03T09:00:00Z",
            updatedAt: "2024-02-03T10:00:00Z",
          },
          {
            id: "31",
            title: "useState Hook",
            description:
              "Managing state in functional components with useState",
            filename: "usestate-hook.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/usestate-hook.mp4",
            createdAt: "2024-02-03T10:00:00Z",
            updatedAt: "2024-02-03T11:00:00Z",
          },
          {
            id: "32",
            title: "State Updates and Re-renders",
            description:
              "Understanding how state changes trigger component re-renders",
            filename: "state-updates.mp4",
            duration: 600,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/state-updates.mp4",
            createdAt: "2024-02-03T11:00:00Z",
            updatedAt: "2024-02-03T12:00:00Z",
          },
          {
            id: "33",
            title: "Lifting State Up",
            description: "Sharing state between components by lifting it up",
            filename: "lifting-state-up.mp4",
            duration: 660,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/lifting-state-up.mp4",
            createdAt: "2024-02-03T12:00:00Z",
            updatedAt: "2024-02-03T13:00:00Z",
          },
          {
            id: "34",
            title: "Complex State Management",
            description: "Managing complex state with objects and arrays",
            filename: "complex-state.mp4",
            duration: 780,
            order: 5,
            status: "processed",
            url: "https://example.com/lessons/complex-state.mp4",
            createdAt: "2024-02-03T13:00:00Z",
            updatedAt: "2024-02-03T14:00:00Z",
          },
          {
            id: "35",
            title: "State Best Practices",
            description: "Best practices for organizing and managing state",
            filename: "state-best-practices.mp4",
            duration: 540,
            order: 6,
            status: "processing",
            createdAt: "2024-02-03T14:00:00Z",
            updatedAt: "2024-02-03T15:00:00Z",
          },
        ],
      },
      {
        id: "10",
        title: "Event Handling",
        description:
          "Handling user interactions and events in React applications",
        order: 4,
        createdAt: "2024-02-04T09:00:00Z",
        updatedAt: "2024-02-04T13:00:00Z",
        lessons: [
          {
            id: "36",
            title: "Event Handling Basics",
            description: "Understanding how events work in React",
            filename: "event-handling-basics.mp4",
            duration: 480,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/event-handling-basics.mp4",
            createdAt: "2024-02-04T09:00:00Z",
            updatedAt: "2024-02-04T10:00:00Z",
          },
          {
            id: "37",
            title: "Form Handling",
            description: "Working with forms and controlled components",
            filename: "form-handling.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/form-handling.mp4",
            createdAt: "2024-02-04T10:00:00Z",
            updatedAt: "2024-02-04T11:00:00Z",
          },
          {
            id: "38",
            title: "Event Object and Synthetic Events",
            description: "Understanding React's synthetic event system",
            filename: "synthetic-events.mp4",
            duration: 420,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/synthetic-events.mp4",
            createdAt: "2024-02-04T11:00:00Z",
            updatedAt: "2024-02-04T12:00:00Z",
          },
          {
            id: "39",
            title: "Conditional Rendering",
            description: "Rendering components conditionally based on state",
            filename: "conditional-rendering.mp4",
            duration: 540,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/conditional-rendering.mp4",
            createdAt: "2024-02-04T12:00:00Z",
            updatedAt: "2024-02-04T13:00:00Z",
          },
        ],
      },
      {
        id: "11",
        title: "Lists and Keys",
        description: "Rendering lists of data and understanding React keys",
        order: 5,
        createdAt: "2024-02-05T09:00:00Z",
        updatedAt: "2024-02-05T12:00:00Z",
        lessons: [
          {
            id: "40",
            title: "Rendering Lists",
            description: "Using map() to render lists of components",
            filename: "rendering-lists.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/rendering-lists.mp4",
            createdAt: "2024-02-05T09:00:00Z",
            updatedAt: "2024-02-05T10:00:00Z",
          },
          {
            id: "41",
            title: "Understanding Keys",
            description: "Why keys are important and how to use them properly",
            filename: "understanding-keys.mp4",
            duration: 480,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/understanding-keys.mp4",
            createdAt: "2024-02-05T10:00:00Z",
            updatedAt: "2024-02-05T11:00:00Z",
          },
          {
            id: "42",
            title: "Dynamic Lists and CRUD Operations",
            description: "Adding, updating, and deleting items in lists",
            filename: "dynamic-lists.mp4",
            duration: 720,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/dynamic-lists.mp4",
            createdAt: "2024-02-05T11:00:00Z",
            updatedAt: "2024-02-05T12:00:00Z",
          },
        ],
      },
      {
        id: "12",
        title: "React Hooks Deep Dive",
        description: "Exploring essential React hooks beyond useState",
        order: 6,
        createdAt: "2024-02-06T09:00:00Z",
        updatedAt: "2024-02-06T15:00:00Z",
        lessons: [
          {
            id: "43",
            title: "useEffect Hook Introduction",
            description: "Understanding side effects and the useEffect hook",
            filename: "useeffect-intro.mp4",
            duration: 660,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/useeffect-intro.mp4",
            createdAt: "2024-02-06T09:00:00Z",
            updatedAt: "2024-02-06T10:00:00Z",
          },
          {
            id: "44",
            title: "useEffect Dependencies",
            description:
              "Understanding dependency arrays and effect optimization",
            filename: "useeffect-dependencies.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/useeffect-dependencies.mp4",
            createdAt: "2024-02-06T10:00:00Z",
            updatedAt: "2024-02-06T11:00:00Z",
          },
          {
            id: "45",
            title: "Cleanup and useEffect",
            description: "Cleaning up effects to prevent memory leaks",
            filename: "useeffect-cleanup.mp4",
            duration: 540,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/useeffect-cleanup.mp4",
            createdAt: "2024-02-06T11:00:00Z",
            updatedAt: "2024-02-06T12:00:00Z",
          },
          {
            id: "46",
            title: "useContext Hook",
            description: "Sharing data across components with Context API",
            filename: "usecontext-hook.mp4",
            duration: 780,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/usecontext-hook.mp4",
            createdAt: "2024-02-06T12:00:00Z",
            updatedAt: "2024-02-06T13:00:00Z",
          },
          {
            id: "47",
            title: "useReducer Hook",
            description: "Managing complex state with useReducer",
            filename: "usereducer-hook.mp4",
            duration: 840,
            order: 5,
            status: "processed",
            url: "https://example.com/lessons/usereducer-hook.mp4",
            createdAt: "2024-02-06T13:00:00Z",
            updatedAt: "2024-02-06T14:00:00Z",
          },
          {
            id: "48",
            title: "Custom Hooks",
            description: "Creating reusable logic with custom hooks",
            filename: "custom-hooks.mp4",
            duration: 720,
            order: 6,
            status: "processing",
            createdAt: "2024-02-06T14:00:00Z",
            updatedAt: "2024-02-06T15:00:00Z",
          },
        ],
      },
      {
        id: "13",
        title: "Styling in React",
        description: "Different approaches to styling React components",
        order: 7,
        createdAt: "2024-02-07T09:00:00Z",
        updatedAt: "2024-02-07T13:00:00Z",
        lessons: [
          {
            id: "49",
            title: "CSS Modules",
            description: "Scoped CSS styling with CSS modules",
            filename: "css-modules.mp4",
            duration: 600,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/css-modules.mp4",
            createdAt: "2024-02-07T09:00:00Z",
            updatedAt: "2024-02-07T10:00:00Z",
          },
          {
            id: "50",
            title: "Styled Components",
            description: "CSS-in-JS with styled-components library",
            filename: "styled-components.mp4",
            duration: 720,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/styled-components.mp4",
            createdAt: "2024-02-07T10:00:00Z",
            updatedAt: "2024-02-07T11:00:00Z",
          },
          {
            id: "51",
            title: "Inline Styles and Dynamic Styling",
            description: "Using inline styles and conditional styling",
            filename: "inline-styles.mp4",
            duration: 480,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/inline-styles.mp4",
            createdAt: "2024-02-07T11:00:00Z",
            updatedAt: "2024-02-07T12:00:00Z",
          },
          {
            id: "52",
            title: "CSS Frameworks with React",
            description:
              "Integrating Bootstrap, Tailwind CSS, and other frameworks",
            filename: "css-frameworks.mp4",
            duration: 540,
            order: 4,
            status: "processing",
            createdAt: "2024-02-07T12:00:00Z",
            updatedAt: "2024-02-07T13:00:00Z",
          },
        ],
      },
      {
        id: "14",
        title: "Building Your First React App",
        description:
          "Putting it all together to build a complete React application",
        order: 8,
        createdAt: "2024-02-08T09:00:00Z",
        updatedAt: "2024-02-08T16:00:00Z",
        lessons: [
          {
            id: "53",
            title: "Planning Your App",
            description: "Breaking down the app into components and features",
            filename: "planning-app.mp4",
            duration: 420,
            order: 1,
            status: "processed",
            url: "https://example.com/lessons/planning-app.mp4",
            createdAt: "2024-02-08T09:00:00Z",
            updatedAt: "2024-02-08T10:00:00Z",
          },
          {
            id: "54",
            title: "Setting Up the Project Structure",
            description: "Organizing files and folders for a React project",
            filename: "project-structure.mp4",
            duration: 360,
            order: 2,
            status: "processed",
            url: "https://example.com/lessons/project-structure.mp4",
            createdAt: "2024-02-08T10:00:00Z",
            updatedAt: "2024-02-08T11:00:00Z",
          },
          {
            id: "55",
            title: "Building Core Components",
            description: "Creating the main components of your application",
            filename: "building-components.mp4",
            duration: 900,
            order: 3,
            status: "processed",
            url: "https://example.com/lessons/building-components.mp4",
            createdAt: "2024-02-08T11:00:00Z",
            updatedAt: "2024-02-08T12:00:00Z",
          },
          {
            id: "56",
            title: "Adding Interactivity",
            description: "Implementing user interactions and state management",
            filename: "adding-interactivity.mp4",
            duration: 840,
            order: 4,
            status: "processed",
            url: "https://example.com/lessons/adding-interactivity.mp4",
            createdAt: "2024-02-08T12:00:00Z",
            updatedAt: "2024-02-08T13:00:00Z",
          },
          {
            id: "57",
            title: "Styling and Polish",
            description: "Adding styles and finishing touches to your app",
            filename: "styling-polish.mp4",
            duration: 720,
            order: 5,
            status: "processed",
            url: "https://example.com/lessons/styling-polish.mp4",
            createdAt: "2024-02-08T13:00:00Z",
            updatedAt: "2024-02-08T14:00:00Z",
          },
          {
            id: "58",
            title: "Testing Your App",
            description: "Basic testing strategies for React applications",
            filename: "testing-app.mp4",
            duration: 600,
            order: 6,
            status: "processed",
            url: "https://example.com/lessons/testing-app.mp4",
            createdAt: "2024-02-08T14:00:00Z",
            updatedAt: "2024-02-08T15:00:00Z",
          },
          {
            id: "59",
            title: "Deployment and Next Steps",
            description: "Deploying your React app and what to learn next",
            filename: "deployment-next-steps.mp4",
            duration: 480,
            order: 7,
            status: "processing",
            createdAt: "2024-02-08T15:00:00Z",
            updatedAt: "2024-02-08T16:00:00Z",
          },
        ],
      },
    ],
  },
];

// Utility functions for working with the embedded structure
export const getCourseBySlug = (slug: string): Course | undefined => {
  return mockCourses.find((course) => course.slug === slug);
};

export const getChapterById = (
  courseSlug: string,
  chapterId: string
): Chapter | undefined => {
  const course = getCourseBySlug(courseSlug);
  return course?.chapters.find((chapter) => chapter.id === chapterId);
};

export const getLessonById = (
  courseId: string,
  chapterId: string,
  lessonId: string
): Lesson | undefined => {
  const chapter = getChapterById(courseId, chapterId);
  return chapter?.lessons.find((lesson) => lesson.id === lessonId);
};

export const getTotalCourseDuration = (course: Course): number => {
  return course.chapters.reduce((courseTotal, chapter) => {
    const chapterTotal = chapter.lessons.reduce(
      (lessonTotal, lesson) => lessonTotal + lesson.duration,
      0
    );
    return courseTotal + chapterTotal;
  }, 0);
};

export const getProcessedLessonsCount = (course: Course): number => {
  return course.chapters.reduce((total, chapter) => {
    const processedInChapter = chapter.lessons.filter(
      (lesson) => lesson.status === "processed"
    ).length;
    return total + processedInChapter;
  }, 0);
};

export const getTotalLessonsCount = (course: Course): number => {
  return course.chapters.reduce(
    (total, chapter) => total + chapter.lessons.length,
    0
  );
};
